apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: auth-gateway
  labels:
    app: gateway
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      port: 97
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: auth-gateway
spec:
  parentRefs:
    - name: jwt-gateway
  rules:
    - matches:
        - path:
            type: Exact
            value: /
      backendRefs:
        - name: spring
          port: 8081
    - matches:
        - path:
            type: PathPrefix
            value: /api/auth/register
      backendRefs:
        - name: auth
          port: 8081
