apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: auth-gateway
  labels:
    app: gateway
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      port: 97
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
