apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: auth-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: virtualservice
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - auth-gateway
  http:
      - match:
        - uri:
            prefix: /authservice/
        rewrite:
         uri: /
        route:
        - destination:
            host: auth-service.default.svc.cluster.local
            port:
              number: 8081
      - match:
        - uri:
            prefix: /postservice/
        rewrite:
          uri: /
        route:
          - destination:
              host: postservice.default.svc.cluster.local
              port:
                number: 8000
